### ISSUE TITLE
3.12.2 python problem with Functor subclass check

### ISSUE THREAD

**Issue by banderlog** [dbrattli/OSlash#35]
Hi, the next error appears on python3.12.2:

```
 File "/venv/lib/python3.12/site-packages/oslash/_init_.py", line 11, in <module>
    from .state import State
  File "/venv/lib/python3.12/site-packages/oslash/state.py", line 78, in <module>
    assert issubclass(State, Functor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 1841, in _subclasscheck_
    cls._non_callable_proto_members_
AttributeError: type object 'Functor' has no attribute '_non_callable_proto_members_'
```

with 3.11 everything is fine

oslash-0.6.3 (latest)

**Comment by banderlog** [comment]
UPD: it is the problem of combination of  python and `typing-extensions`

python-3.12 with typing-extensions>4.9.0 fails  
python-3.10 and python-3.11 works fine with typing-extensions>=4.9.0

**Comment by banderlog** [comment]
https://github.com/python/typing_extensions/issues/372#issuecomment-2067787722

>Thanks. This happens because you're mixing typing.Protocol with typing_extensions.runtime_checkable. If you either import both symbols from typing or both symbols from typing_extensions, the error goes away.

**Comment by simonzg** [comment]
I know I might be asking for too much, but do you have any timeline in mind to publish a fix soon? I'm experiencing this exact error and would like to get it fixed soon. Thanks in advance. @banderlog

**Comment by banderlog** [comment]
@simonzg  https://github.com/dbrattli/OSlash/pull/36

or hardcode specific version `typing-extensions==4.9.0` in requirements/toml file
